package command.commands

import command.baseclasses.CommandArgument
import command.baseclasses.CommandLiteral
import command.baseclasses.CommandNode
import vector.Coordinates
import target.Selector

class RootCommand(
    parent: CommandNode?,
    literal: String? = "root"
): CommandLiteral(parent, literal) {
    val advancement = RootAdvancementCommand(this)
    val attribute = RootAttributeCommand(this)
    val ban = RootBanCommand(this)
    val banIp = RootBanIpCommand(this)
    val banlist = RootBanlistCommand(this)
    val bossbar = RootBossbarCommand(this)
    val clear = RootClearCommand(this)
    val clone = RootCloneCommand(this)
    val data = RootDataCommand(this)
    val datapack = RootDatapackCommand(this)
    val debug = RootDebugCommand(this)
    val defaultgamemode = RootDefaultgamemodeCommand(this)
    val deop = RootDeopCommand(this)
    val difficulty = RootDifficultyCommand(this)
    val effect = RootEffectCommand(this)
    val enchant = RootEnchantCommand(this)
    val experience = RootExperienceCommand(this)
    val fill = RootFillCommand(this)
    val forceload = RootForceloadCommand(this)
    val function = RootFunctionCommand(this)
    val gamemode = RootGamemodeCommand(this)
    val gamerule = RootGameruleCommand(this)
    val give = RootGiveCommand(this)
    val help = RootHelpCommand(this)
    val kick = RootKickCommand(this)
    val kill = RootKillCommand(this)
    val list = RootListCommand(this)
    val locate = RootLocateCommand(this)
    val locatebiome = RootLocatebiomeCommand(this)
    val loot = RootLootCommand(this)
    val me = RootMeCommand(this)
    val msg = RootMsgCommand(this)
    val op = RootOpCommand(this)
    val pardon = RootPardonCommand(this)
    val pardonIp = RootPardonIpCommand(this)
    val particle = RootParticleCommand(this)
    val playsound = RootPlaysoundCommand(this)
    val publish = RootPublishCommand(this)
    val recipe = RootRecipeCommand(this)
    val reload = RootReloadCommand(this)
    val replaceitem = RootReplaceitemCommand(this)
    val saveAll = RootSaveAllCommand(this)
    val saveOff = RootSaveOffCommand(this)
    val saveOn = RootSaveOnCommand(this)
    val say = RootSayCommand(this)
    val schedule = RootScheduleCommand(this)
    val scoreboard = RootScoreboardCommand(this)
    val seed = RootSeedCommand(this)
    val setblock = RootSetblockCommand(this)
    val setidletimeout = RootSetidletimeoutCommand(this)
    val setworldspawn = RootSetworldspawnCommand(this)
    val spawnpoint = RootSpawnpointCommand(this)
    val spectate = RootSpectateCommand(this)
    val spreadplayers = RootSpreadplayersCommand(this)
    val stop = RootStopCommand(this)
    val stopsound = RootStopsoundCommand(this)
    val summon = RootSummonCommand(this)
    val tag = RootTagCommand(this)
    val team = RootTeamCommand(this)
    val teammsg = RootTeammsgCommand(this)
    val teleport = RootTeleportCommand(this)
    val tell = RootTellCommand(this).redirect()
    val tellraw = RootTellrawCommand(this)
    val time = RootTimeCommand(this)
    val title = RootTitleCommand(this)
    val tm = RootTmCommand(this).redirect()
    val tp = RootTpCommand(this).redirect()
    val trigger = RootTriggerCommand(this)
    val w = RootWCommand(this).redirect()
    val weather = RootWeatherCommand(this)
    val whitelist = RootWhitelistCommand(this)
    val worldborder = RootWorldborderCommand(this)
    val xp = RootXpCommand(this).redirect()
}
